on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: pip install requests
      - name: Generate index.html
        env:
          MY_ACCESS_TOKEN: ${{ secrets.MY_ACCESS_TOKEN }}
        run: python ./generate-index.py
      - name: Set up Git
        run: |
          git config --global user.name "iamargelh"
          git config --global user.email "youremail@example.com"
          git config --global credential.helper store
          echo "protocol=https\nhost=github.com\nusername=iamargelh\npassword=${{ secrets.MY_ACCESS_TOKEN }}" > $HOME/.git-credentials
      - name: Commit and push changes
        run: |
          git add tree.json
          #git add tree.xml
          git commit -m "Update trees"
          git push
