on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: List files
        run: ls -al
      - name: Generate index.html
        run: bash ./generate-index.sh
